[package]
name = "skychat"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
openmls = "0.6.0"
openmls_basic_credential = "0.3.0"
openmls_rust_crypto = "0.3.0"
rand = "0.9.0"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.13.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
serde_json = { version = "1.0" }
serde = { version = "1.0.217", features = ["derive"] }
ratatui = "0.22.0"
crossterm = "0.26.0"
base64 = "0.22.1"
reqwest = { version = "0.12", features = ["json"] }
rocket = { version = "0.5.1", features = ["json"] }


[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[bin]]
name = "tui"
path = "src/bin/tui.rs"
