// Generated by uniffi-bindgen-react-native
import installer from './NativeSkychatLib';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
export * from './generated/foobar';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as foobar from './generated/foobar';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  foobar.default.initialize();
  initialized = true;
}

// Export the crates as individually namespaced objects.
export default {
  foobar,
};

export { ConvoProvider, useConvo } from './contexts/ConvoContext';
export { ChatProvider } from './contexts/ChatContext';
export { ChatList } from './components/chat/ChatList';
export { ChatItem, User, Chat } from './components/chat/ChatItem';
export { NewChatModal } from './components/chat/NewChat';
export { BskyChat } from './components/chat/BskyChat';
// export { useThemeProvider as useChatThemeProvider } from './utils/useAppTheme';
export { ChatMessageBox } from './components/chat/ChatMessageBox';
export { ReplyMessageBar } from './components/chat/ReplyMessageBar';
export { ChatRequestsList } from './components/chat/ChatRequestsList';
export { ChatRequestItem } from './components/chat/ChatItem';
export { ChatSettings } from './components/bsky/ChatSettings';
export { SearchCreate } from './components/chat/SearchCreate';
export { AccountBackup } from './components/bsky/AccountBackup';
