[package]
name = "skychat_server"
version = "0.1.0"
edition = "2021"

[dependencies]
skychat-core = { path = "../core" }
serde_json.workspace = true
serde.workspace = true
anyhow.workspace = true
tokio.workspace = true