// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(foobarFFI)
import foobarFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_foobar_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_foobar_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol ConvoManagerProtocol : AnyObject {
    
    func createInvite(groupId: Data, keyPackage: Data)  -> ConvoInviteWrapper
    
    func createMessage(groupId: Data, message: String)  -> Data
    
    func createNewGroup(name: String)  -> Data
    
    func getGroupEpoch(groupId: Data)  -> UInt64
    
    func getKeyPackage()  -> Data
    
    func getPartialGroup(groupId: Data)  -> LocalGroupWrapper
    
    func processMessage(message: Data, senderId: String?)  -> ProcessedResultsWrapper
    
    func processRawInvite(groupName: String, welcomeMessage: Data, ratchetTree: Data?, keyPackage: Data?) 
    
}

open class ConvoManager:
    ConvoManagerProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_foobar_fn_clone_convomanager(self.pointer, $0) }
    }
public convenience init(name: String) {
    let pointer =
        try! rustCall() {
    uniffi_foobar_fn_constructor_convomanager_new(
        FfiConverterString.lower(name),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_foobar_fn_free_convomanager(pointer, $0) }
    }

    

    
open func createInvite(groupId: Data, keyPackage: Data) -> ConvoInviteWrapper {
    return try!  FfiConverterTypeConvoInviteWrapper.lift(try! rustCall() {
    uniffi_foobar_fn_method_convomanager_create_invite(self.uniffiClonePointer(),
        FfiConverterData.lower(groupId),
        FfiConverterData.lower(keyPackage),$0
    )
})
}
    
open func createMessage(groupId: Data, message: String) -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_foobar_fn_method_convomanager_create_message(self.uniffiClonePointer(),
        FfiConverterData.lower(groupId),
        FfiConverterString.lower(message),$0
    )
})
}
    
open func createNewGroup(name: String) -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_foobar_fn_method_convomanager_create_new_group(self.uniffiClonePointer(),
        FfiConverterString.lower(name),$0
    )
})
}
    
open func getGroupEpoch(groupId: Data) -> UInt64 {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_foobar_fn_method_convomanager_get_group_epoch(self.uniffiClonePointer(),
        FfiConverterData.lower(groupId),$0
    )
})
}
    
open func getKeyPackage() -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_foobar_fn_method_convomanager_get_key_package(self.uniffiClonePointer(),$0
    )
})
}
    
open func getPartialGroup(groupId: Data) -> LocalGroupWrapper {
    return try!  FfiConverterTypeLocalGroupWrapper.lift(try! rustCall() {
    uniffi_foobar_fn_method_convomanager_get_partial_group(self.uniffiClonePointer(),
        FfiConverterData.lower(groupId),$0
    )
})
}
    
open func processMessage(message: Data, senderId: String?) -> ProcessedResultsWrapper {
    return try!  FfiConverterTypeProcessedResultsWrapper.lift(try! rustCall() {
    uniffi_foobar_fn_method_convomanager_process_message(self.uniffiClonePointer(),
        FfiConverterData.lower(message),
        FfiConverterOptionString.lower(senderId),$0
    )
})
}
    
open func processRawInvite(groupName: String, welcomeMessage: Data, ratchetTree: Data?, keyPackage: Data?) {try! rustCall() {
    uniffi_foobar_fn_method_convomanager_process_raw_invite(self.uniffiClonePointer(),
        FfiConverterString.lower(groupName),
        FfiConverterData.lower(welcomeMessage),
        FfiConverterOptionData.lower(ratchetTree),
        FfiConverterOptionData.lower(keyPackage),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConvoManager: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ConvoManager

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ConvoManager {
        return ConvoManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ConvoManager) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConvoManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ConvoManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConvoManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> ConvoManager {
    return try FfiConverterTypeConvoManager.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConvoManager_lower(_ value: ConvoManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypeConvoManager.lower(value)
}


public struct ConvoInviteWrapper {
    public var groupName: String
    public var welcomeMessage: Data
    public var ratchetTree: Data?
    public var globalIndex: UInt64
    public var fanned: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(groupName: String, welcomeMessage: Data, ratchetTree: Data?, globalIndex: UInt64, fanned: Data?) {
        self.groupName = groupName
        self.welcomeMessage = welcomeMessage
        self.ratchetTree = ratchetTree
        self.globalIndex = globalIndex
        self.fanned = fanned
    }
}



extension ConvoInviteWrapper: Equatable, Hashable {
    public static func ==(lhs: ConvoInviteWrapper, rhs: ConvoInviteWrapper) -> Bool {
        if lhs.groupName != rhs.groupName {
            return false
        }
        if lhs.welcomeMessage != rhs.welcomeMessage {
            return false
        }
        if lhs.ratchetTree != rhs.ratchetTree {
            return false
        }
        if lhs.globalIndex != rhs.globalIndex {
            return false
        }
        if lhs.fanned != rhs.fanned {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(groupName)
        hasher.combine(welcomeMessage)
        hasher.combine(ratchetTree)
        hasher.combine(globalIndex)
        hasher.combine(fanned)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConvoInviteWrapper: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConvoInviteWrapper {
        return
            try ConvoInviteWrapper(
                groupName: FfiConverterString.read(from: &buf), 
                welcomeMessage: FfiConverterData.read(from: &buf), 
                ratchetTree: FfiConverterOptionData.read(from: &buf), 
                globalIndex: FfiConverterUInt64.read(from: &buf), 
                fanned: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: ConvoInviteWrapper, into buf: inout [UInt8]) {
        FfiConverterString.write(value.groupName, into: &buf)
        FfiConverterData.write(value.welcomeMessage, into: &buf)
        FfiConverterOptionData.write(value.ratchetTree, into: &buf)
        FfiConverterUInt64.write(value.globalIndex, into: &buf)
        FfiConverterOptionData.write(value.fanned, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConvoInviteWrapper_lift(_ buf: RustBuffer) throws -> ConvoInviteWrapper {
    return try FfiConverterTypeConvoInviteWrapper.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConvoInviteWrapper_lower(_ value: ConvoInviteWrapper) -> RustBuffer {
    return FfiConverterTypeConvoInviteWrapper.lower(value)
}


public struct LocalGroupWrapper {
    public var name: String
    public var globalIndex: UInt64
    public var decrypted: [MessageItemWrapper]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, globalIndex: UInt64, decrypted: [MessageItemWrapper]) {
        self.name = name
        self.globalIndex = globalIndex
        self.decrypted = decrypted
    }
}



extension LocalGroupWrapper: Equatable, Hashable {
    public static func ==(lhs: LocalGroupWrapper, rhs: LocalGroupWrapper) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.globalIndex != rhs.globalIndex {
            return false
        }
        if lhs.decrypted != rhs.decrypted {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(globalIndex)
        hasher.combine(decrypted)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocalGroupWrapper: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocalGroupWrapper {
        return
            try LocalGroupWrapper(
                name: FfiConverterString.read(from: &buf), 
                globalIndex: FfiConverterUInt64.read(from: &buf), 
                decrypted: FfiConverterSequenceTypeMessageItemWrapper.read(from: &buf)
        )
    }

    public static func write(_ value: LocalGroupWrapper, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt64.write(value.globalIndex, into: &buf)
        FfiConverterSequenceTypeMessageItemWrapper.write(value.decrypted, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocalGroupWrapper_lift(_ buf: RustBuffer) throws -> LocalGroupWrapper {
    return try FfiConverterTypeLocalGroupWrapper.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocalGroupWrapper_lower(_ value: LocalGroupWrapper) -> RustBuffer {
    return FfiConverterTypeLocalGroupWrapper.lower(value)
}


public struct MessageItemWrapper {
    public var text: String
    public var senderId: String
    public var timestamp: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(text: String, senderId: String, timestamp: UInt64) {
        self.text = text
        self.senderId = senderId
        self.timestamp = timestamp
    }
}



extension MessageItemWrapper: Equatable, Hashable {
    public static func ==(lhs: MessageItemWrapper, rhs: MessageItemWrapper) -> Bool {
        if lhs.text != rhs.text {
            return false
        }
        if lhs.senderId != rhs.senderId {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text)
        hasher.combine(senderId)
        hasher.combine(timestamp)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMessageItemWrapper: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MessageItemWrapper {
        return
            try MessageItemWrapper(
                text: FfiConverterString.read(from: &buf), 
                senderId: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: MessageItemWrapper, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterString.write(value.senderId, into: &buf)
        FfiConverterUInt64.write(value.timestamp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageItemWrapper_lift(_ buf: RustBuffer) throws -> MessageItemWrapper {
    return try FfiConverterTypeMessageItemWrapper.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMessageItemWrapper_lower(_ value: MessageItemWrapper) -> RustBuffer {
    return FfiConverterTypeMessageItemWrapper.lower(value)
}


public struct ProcessedResultsWrapper {
    public var message: String?
    public var invite: ConvoInviteWrapper?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(message: String?, invite: ConvoInviteWrapper?) {
        self.message = message
        self.invite = invite
    }
}



extension ProcessedResultsWrapper: Equatable, Hashable {
    public static func ==(lhs: ProcessedResultsWrapper, rhs: ProcessedResultsWrapper) -> Bool {
        if lhs.message != rhs.message {
            return false
        }
        if lhs.invite != rhs.invite {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(message)
        hasher.combine(invite)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProcessedResultsWrapper: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProcessedResultsWrapper {
        return
            try ProcessedResultsWrapper(
                message: FfiConverterOptionString.read(from: &buf), 
                invite: FfiConverterOptionTypeConvoInviteWrapper.read(from: &buf)
        )
    }

    public static func write(_ value: ProcessedResultsWrapper, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.message, into: &buf)
        FfiConverterOptionTypeConvoInviteWrapper.write(value.invite, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProcessedResultsWrapper_lift(_ buf: RustBuffer) throws -> ProcessedResultsWrapper {
    return try FfiConverterTypeProcessedResultsWrapper.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProcessedResultsWrapper_lower(_ value: ProcessedResultsWrapper) -> RustBuffer {
    return FfiConverterTypeProcessedResultsWrapper.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeConvoInviteWrapper: FfiConverterRustBuffer {
    typealias SwiftType = ConvoInviteWrapper?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeConvoInviteWrapper.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeConvoInviteWrapper.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMessageItemWrapper: FfiConverterRustBuffer {
    typealias SwiftType = [MessageItemWrapper]

    public static func write(_ value: [MessageItemWrapper], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMessageItemWrapper.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MessageItemWrapper] {
        let len: Int32 = try readInt(&buf)
        var seq = [MessageItemWrapper]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMessageItemWrapper.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_foobar_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_foobar_checksum_method_convomanager_create_invite() != 50076) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_foobar_checksum_method_convomanager_create_message() != 101) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_foobar_checksum_method_convomanager_create_new_group() != 44787) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_foobar_checksum_method_convomanager_get_group_epoch() != 35913) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_foobar_checksum_method_convomanager_get_key_package() != 58549) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_foobar_checksum_method_convomanager_get_partial_group() != 51255) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_foobar_checksum_method_convomanager_process_message() != 22503) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_foobar_checksum_method_convomanager_process_raw_invite() != 34162) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_foobar_checksum_constructor_convomanager_new() != 51625) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all